[project]
name = "ucdm-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==5.2.8",
    "django-extensions==4.1",
    "fabric==3.2.2",
    "python-telegram-bot[job-queue]==22.5",
    "toml==0.10.2",
]
